export const GET_ITEMS_INITIATED = 'GET_ITEMS_INITIATED';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILED = 'GET_ITEMS_FAILED';

export const LOGIN_USER_INITIATED = 'LOGIN_USER_INITIATED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';