export const GET_ITEMS_INITIATED = 'GET_ITEMS_INITIATED';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILED = 'GET_ITEMS_FAILED';

export const LOGIN_USER_INITIATED = 'LOGIN_USER_INITIATED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const REGISTER_USER_INITIATED = 'REGISTER_USER_INITIATED';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';

export const LOGOUT_USER = 'LOGOUT_USER';

export const CREATE_ITEM_INITIATED = 'CREATE_ITEM_INITIATED';
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';
export const CREATE_ITEM_FAILED = 'CREATE_ITEM_FAILED';

export const UPDATE_ITEM_INITIATED = 'UPDATE_ITEM_INITIATED';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const UPDATE_ITEM_FAILED = 'UPDATE_ITEM_FAILED';

export const DELETE_ITEM_INITIATED = 'DELETE_ITEM_INITIATED';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAILED = 'DELETE_ITEM_FAILED';
