export const GET_BLOGS_INITIATED = 'GET_BLOGS_INITIATED'
export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS'
export const GET_BLOGS_FAILED = 'GET_BLOGS_FAILED'

export const CREATE_BLOG_INITIATED = 'CREATE_BLOG_INITIATED'
export const CREATE_BLOG_SUCCESS = 'CREATE_BLOG_SUCCESS'
export const CREATE_BLOG_FAILED = 'CREATE_BLOG_FAILED'

export const UPDATE_BLOG_INITIATED = 'UPDATE_BLOG_INITIATED'
export const UPDATE_BLOG_SUCCESS = 'UPDATE_BLOG_SUCCESS'
export const UPDATE_BLOG_FAILED = 'UPDATE_BLOG_FAILED'

export const UPDATE_LIKE_INITIATED = 'UPDATE_LIKE_INITIATED'
export const UPDATE_LIKE_SUCCESS = 'UPDATE_LIKE_SUCCESS'
export const UPDATE_LIKE_FAILED = 'UPDATE_LIKE_FAILED'