export const REGISTER_USER_INITIATED = 'REGISTER_USER_INITIATED'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED'

export const LOGIN_USER_INITIATED = 'LOGIN_USER_INITIATED'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED'

export const LOAD_USER_INITIATED = 'LOAD_USER_INITIATED'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAILED = 'LOAD_USER_FAILED'

export const LOAD_GOALS_INITIATED = 'LOAD_GOALS_INITIATED'
export const LOAD_GOALS_SUCCESS = 'LOAD_GOALS_SUCCESS'
export const LOAD_GOALS_FAILED = 'LOAD_GOALS_FAILED'

export const CREATE_GOAL_INITIATED = 'CREATE_GOAL_INITIATED'
export const CREATE_GOAL_SUCCESS = 'CREATE_GOAL_SUCCESS'
export const CREATE_GOAL_FAILED = 'CREATE_GOAL_FAILED'

export const UPDATE_GOAL_INITIATED = 'UPDATE_GOAL_INITIATED'
export const UPDATE_GOAL_SUCCESS = 'UPDATE_GOAL_SUCCESS'
export const UPDATE_GOAL_FAILED = 'UPDATE_GOAL_FAILED'